import { NextRequest, NextResponse } from 'next/server';

// Free image generation using Pollinations.ai
// No API key required - generates images via URL

interface GenerateRequest {
  prompt: string;
  style?: 'realistic' | 'anime' | 'digital-art' | 'cinematic';
  width?: number;
  height?: number;
}

export async function POST(request: NextRequest) {
  try {
    const body: GenerateRequest = await request.json();
    const { prompt, style = 'digital-art', width = 1024, height = 1024 } = body;

    if (!prompt || prompt.trim().length < 5) {
      return NextResponse.json(
        { error: 'Prompt must be at least 5 characters' },
        { status: 400 }
      );
    }

    // Style modifiers to enhance prompts
    const styleModifiers: Record<string, string> = {
      'realistic': 'photorealistic, high detail, 8k resolution, professional photography',
      'anime': 'anime style, vibrant colors, clean lines, studio ghibli inspired',
      'digital-art': 'digital art, modern design, clean aesthetic, trending on artstation',
      'cinematic': 'cinematic, dramatic lighting, movie poster style, epic composition',
    };

    // Build enhanced prompt
    const enhancedPrompt = `${prompt}, ${styleModifiers[style] || styleModifiers['digital-art']}`;

    // Pollinations.ai generates images via URL
    // The image is generated on-demand when the URL is accessed
    const encodedPrompt = encodeURIComponent(enhancedPrompt);
    const imageUrl = `https://image.pollinations.ai/prompt/${encodedPrompt}?width=${width}&height=${height}&nologo=true`;

    // Verify the image can be generated by making a HEAD request
    try {
      const checkResponse = await fetch(imageUrl, { method: 'HEAD' });
      if (!checkResponse.ok) {
        throw new Error('Image generation failed');
      }
    } catch (fetchError) {
      // If HEAD fails, still return the URL - it may work on direct access
      console.warn('HEAD check failed, returning URL anyway:', fetchError);
    }

    return NextResponse.json({
      imageUrl,
      prompt: enhancedPrompt,
      originalPrompt: prompt,
      style,
      width,
      height,
      provider: 'pollinations.ai',
      _note: 'Image generated on-demand when URL is accessed',
    });
  } catch (error) {
    console.error('Image generation error:', error);
    return NextResponse.json(
      { error: 'Failed to generate image' },
      { status: 500 }
    );
  }
}

// GET endpoint to check service status
export async function GET() {
  return NextResponse.json({
    status: 'available',
    provider: 'pollinations.ai',
    features: ['free', 'no-api-key', 'on-demand-generation'],
    supportedStyles: ['realistic', 'anime', 'digital-art', 'cinematic'],
    limits: {
      maxWidth: 1920,
      maxHeight: 1920,
    },
  });
}
